import type { CollectionConfig } from 'payload'
import { isAuthenticated } from '@/lib/access'

export const ProjectMemberships: CollectionConfig = {
  slug: 'project-memberships',
  labels: {
    singular: { en: 'Project membership', de: 'Projektmitgliedschaft' },
    plural: { en: 'Project memberships', de: 'Projektmitgliedschaften' },
  },
  access: {
    read: isAuthenticated,
    create: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  fields: [
    { name: 'user', type: 'relationship', relationTo: 'users', required: true, label: { en: 'User', de: 'Benutzer:in' } },
    { name: 'project', type: 'relationship', relationTo: 'projects', required: true, label: { en: 'Project', de: 'Projekt' } },
    {
      name: 'role',
      type: 'select',
      label: { en: 'Role', de: 'Rolle' },
      required: true,
      options: [
        { label: { en: 'Project manager', de: 'Projektmanager' }, value: 'PM' },
        { label: { en: 'Citizen', de: 'Bürger:in' }, value: 'Citizen' },
      ],
    },
    {
      name: 'order',
      type: 'number',
      label: { en: 'Order (dashboard)', de: 'Reihenfolge (Dashboard)' },
      defaultValue: 0,
      admin: {
        hidden: true,
      },
    },
    {
      name: 'starred',
      type: 'checkbox',
      label: { en: 'Starred', de: 'Favorit' },
      defaultValue: false,
    },
    {
      name: 'status',
      type: 'select',
      label: { en: 'Status', de: 'Status' },
      defaultValue: 'active',
      options: [
        { label: { en: 'Requested', de: 'Angefragt' }, value: 'requested' },
        { label: { en: 'Active', de: 'Aktiv' }, value: 'active' },
        { label: { en: 'Invited', de: 'Eingeladen' }, value: 'invited' },
        { label: { en: 'Rejected', de: 'Abgelehnt' }, value: 'rejected' },
      ],
    },
    {
      // Invitation code — generated by the PM; redeeming it activates the
      // membership (status invited → active). Cleared once redeemed.
      name: 'inviteCode',
      type: 'text',
      label: { en: 'Invitation code', de: 'Einladungscode' },
      admin: {
        hidden: true,
        description: {
          en: 'Redeemable invitation code for this membership (invited status).',
          de: 'Einlösbarer Einladungscode für diese Mitgliedschaft (Status „Eingeladen”).',
        },
      },
    },
    {
      // Team tags (from the project's `teams` catalog). A membership tagged
      // with a team can see TEAM-visibility content scoped to that team.
      name: 'teams',
      type: 'text',
      hasMany: true,
      label: { en: 'Teams', de: 'Teams' },
      admin: {
        description: {
          en: 'Team tags this member belongs to (must match the project team catalog).',
          de: 'Team-Tags, zu denen diese Person gehört (müssen dem Projekt-Team-Katalog entsprechen).',
        },
      },
    },
  ],
}
